version: '3'
services:
  auth:
    build:
      context: ./auth
    ports:
      - "9001:9001"
  cart:
    build:
      context: ./cart
    ports:
      - "9006:9006"
  catalog:
    build:
      context: ./catalog
    ports:
      - "9002:9002"
  order:
    build:
      context: ./order
    ports:
      - "9004:9004"
  rating:
    build:
      context: ./rating
    ports:
      - "9003:9003"
  web-app:
    build:
      context: ./web-app
    ports:
      - "9005:9005"
