version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: duvidas-dividas-news
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - duvidas_dividas_network
  auth:
    container_name: auth
    build:
      context: ./auth
    volumes:
      - ./auth:/usr/src/app
    ports:
      - "9001:9001"
    networks:
      - duvidas_dividas_network
  cart:
    container_name: cart
    build:
      context: ./cart
    volumes:
      - ./cart:/usr/src/app
    ports:
      - "9006:9006"
    networks:
      - duvidas_dividas_network
  catalog:
    container_name: catalog
    build:
      context: ./catalog
    volumes:
      - ./catalog:/usr/src/app
    ports:
      - "9002:9002"
    networks:
      - duvidas_dividas_network
  order:
    container_name: order
    build:
      context: ./order
    ports:
      - "9004:9004"
    volumes:
      - ./order:/usr/src/app
    networks:
      - duvidas_dividas_network
  rating:
    container_name: rating
    build:
      context: ./rating
    volumes:
      - ./rating:/usr/src/app
    ports:
      - "9003:9003"
    networks:
      - duvidas_dividas_network
  gateway:
    container_name: gateway
    build:
      context: ./gateway
    volumes:
      - ./gateway:/usr/src/app
    ports:
      - "9007:9007"
    networks:
      - duvidas_dividas_network
  web-app:
    container_name: webapp
    build:
      context: ./web-app
    volumes:
      - ./web-app:/usr/src/app
    ports:
      - "9005:9005"
    networks:
      - duvidas_dividas_network
networks:
  duvidas_dividas_network:
