apiVersion: v1
kind: Namespace
metadata:
  name: duvidas-dividas

---
# MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: root
            - name: MONGO_INITDB_DATABASE
              value: duvidas-dividas-news

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb
  type: NodePort  # Expondo o serviço no NodePort

---
# Auth Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: viniciusbeckerbernardini/duvidas-dividas-auth:latest
          ports:
            - containerPort: 9001

---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  selector:
    app: auth
  type: NodePort  # Expondo o serviço no NodePort

---
# Cart Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: viniciusbeckerbernardini/duvidas-dividas-cart:latest
          ports:
            - containerPort: 9006

---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9006
      targetPort: 9006
  selector:
    app: cart
  type: NodePort  # Expondo o serviço no NodePort

---
# Catalog Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: viniciusbeckerbernardini/duvidas-dividas-catalog:latest
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  selector:
    app: catalog
  type: NodePort  # Expondo o serviço no NodePort

---
# Order Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: viniciusbeckerbernardini/duvidas-dividas-order:latest
          ports:
            - containerPort: 9004

---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9004
      targetPort: 9004
  selector:
    app: order
  type: NodePort  # Expondo o serviço no NodePort

---
# Rating Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          image: viniciusbeckerbernardini/duvidas-dividas-rating:latest
          ports:
            - containerPort: 9003

---
apiVersion: v1
kind: Service
metadata:
  name: rating
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  selector:
    app: rating
  type: NodePort  # Expondo o serviço no NodePort

---
# Gateway
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: viniciusbeckerbernardini/duvidas-dividas-gateway:latest
          ports:
            - containerPort: 9007

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9007
      targetPort: 9007
  selector:
    app: gateway
  type: NodePort  # Expondo o serviço no NodePort

---
# Web App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: duvidas-dividas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: viniciusbeckerbernardini/duvidas-dividas-web-app:latest
          ports:
            - containerPort: 9005

---
apiVersion: v1
kind: Service
metadata:
  name: web-app
  namespace: duvidas-dividas
spec:
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 9005
  selector:
    app: web-app
  type: NodePort  # Expondo o serviço no NodePort
